themes:
  dark:
    background: "#000000"
    foreground: "#ffffff"
  light:
    foreground: "#000000"
    background: "#ffffff"

files:
  custom_format: 
    path: "./test-configs/custom-format"
    # This is the default comment symbol
    comment: "#"
    # Do whatever you want with your keys and values!
    format: "set my_<key> as <value>"

  quot_comment: 
    path: "./test-configs/qouts"
    comment: "\""

  custom: 
    path: "./test-configs/custom"
    # NOTE: <COLORS> directive puts every colors just as normal. It can be used when you need
    # additional data around your colors
    # NOTE: Even comments will be added to your config
    custom: |
        # So this is my colors for theme <NAME>:
        <COLORS>
        # Also dont forget that my background color is <BACKGROUND>
  # TODO: Alias, Ignoring
