# You can find more info on how to use this configuration file in Themer's wiki

# Uncomment to specify shell command that will run after `themer set`
# reload: "i3 restart"

# place your themes' variables here
themes:
   theme_name:
     var1: value
     var2: value

# list files you want to be managed by Themer
files:
  file_name:
    path: "/path/to/file" # required
    # List of theme's variables that should be ignored
    ignore: []
    # Keep only needed variables (have more priority than `ignore`
    only: []
    # Rename variables, if needed
    aliases: 
      # The syntax is: `new_name: old_name`
      foo: var1
      bar: var2
    # This tells Themer which character(s) is considered a single line comment
    comment: "#" # default value
    closing_comment: "" # May be needed for files like .css, so you have something like /* THEMER */ comments
    # You may need to change this since different configs support different ways of assigning variables
    format: "<key> = <value>" # default
    custom: |
      # This block will override default Themer's block
      # Also you can place variables in here
      # A signle varialbe
      theme_name = "<name>"
      the_black_color = "<black>";
      # You can import any files you need to embed here.
      # Imports are dynamic - specify any variable inside import path!
      <import ~/themes/<name>/themer-embed.txt>
      # All variables at once (basically, it places the default Themer block in your custom code)
      <colors>
  mutliple_codeblocks:
    path: "/path/to/file"
    comment: "\""
    closing_comment: ""

    # Blocks represent a code block with a tag inside your config file
    # Instead of:
    # # THEMER
    # content here.. 
    # # THEMER_END
    #
    # Each Themer block comment will be suffixed with a block name like this:
    # # THEMER:blockname 
    # content here.. 
    # # THEMER_END:blockname
    blocks:
      # For this block your Themer block should look like this 
      # (notice using a double qoute as the comment line sequece):
      
      # " THEMER:vars
      # " THEMER_END:vars
      vars:
        # Here you can set any of the known values except `path`, `comment` & `closing_comment`
        # since these values already set for the current file
        format: "let <key> = <value>"

